main: "org.ensimag.myplugin.PluginMain"
version: "1.0"
name: "test-minecraft-plugin"
api-version: "1.17"

commands:
   uwu:
      description: Donne du diams + brique lol
      usage: /uwu
   sortchest:
      description: Active/Désactive le tri des coffres
      usage: "Usage : /sortchest [true|false]"
   ninjamode:
      description: Active/Désactive le mode ninja
      usage: "Usage : /ninjamode [enable|disable]"

